// <!-- SPDX-License-Identifier: Apache-2.0 -->
// Maker and Checker
export const PRIVILEGES = {
  // Rule Management 
  SECURITY_CREATE_RULE: 'SECURITY_CREATE_RULE',
  SECURITY_UPDATE_RULE: 'SECURITY_UPDATE_RULE',
  SECURITY_DELETE_RULE: 'SECURITY_DELETE_RULE',
  SECURITY_DISABLE_RULE: 'SECURITY_DISABLE_RULE',
  SECURITY_GET_RULE: 'SECURITY_GET_RULE',
  SECURITY_GET_RULES: 'SECURITY_GET_RULES',

  SECURITY_APPROVE_RULE: 'SECURITY_APPROVE_RULE',
  SECURITY_REJECT_RULE: 'SECURITY_REJECT_RULE',
  SECURITY_WITHDRAW_RULE: 'SECURITY_WITHDRAW_RULE',
  SECURITY_DEPLOY_RULE: 'SECURITY_DEPLOY_RULE',
  SECURITY_RETIRE_RULE: 'SECURITY_RETIRE_RULE',
  SECURITY_ARCHIVE_RULE: 'SECURITY_ARCHIVE_RULE',
  SECURITY_ABANDON_RULE: 'SECURITY_ABANDON_RULE',

  // Rule Config Management 
  SECURITY_CREATE_RULE_CONFIG: 'SECURITY_CREATE_RULE_CONFIG',
  SECURITY_UPDATE_RULE_CONFIG: 'SECURITY_UPDATE_RULE_CONFIG',
  SECURITY_DELETE_RULE_CONFIG: 'SECURITY_DELETE_RULE_CONFIG',
  SECURITY_DISABLE_RULE_CONFIG: 'SECURITY_DISABLE_RULE_CONFIG',
  SECURITY_GET_RULE_CONFIG: 'SECURITY_GET_RULE_CONFIG',
  SECURITY_GET_RULE_CONFIGS: 'SECURITY_GET_RULE_CONFIGS',
  SECURITY_GET_RULE_RULE_CONFIG: 'SECURITY_GET_RULE_RULE_CONFIG',

  SECURITY_APPROVE_RULE_CONFIG: 'SECURITY_APPROVE_RULE_CONFIG',
  SECURITY_REJECT_RULE_CONFIG: 'SECURITY_REJECT_RULE_CONFIG',
  SECURITY_WITHDRAW_RULE_CONFIG: 'SECURITY_WITHDRAW_RULE_CONFIG',
  SECURITY_DEPLOY_RULE_CONFIG: 'SECURITY_DEPLOY_RULE_CONFIG',
  SECURITY_RETIRE_RULE_CONFIG: 'SECURITY_RETIRE_RULE_CONFIG',
  SECURITY_ARCHIVE_RULE_CONFIG: 'SECURITY_ARCHIVE_RULE_CONFIG',
  SECURITY_ABANDON_RULE_CONFIG: 'SECURITY_ABANDON_RULE_CONFIG',

  // Typology Management 
  SECURITY_CREATE_TYPOLOGY: 'SECURITY_CREATE_TYPOLOGY',
  SECURITY_UPDATE_TYPOLOGY: 'SECURITY_UPDATE_TYPOLOGY',
  SECURITY_DELETE_TYPOLOGY: 'SECURITY_DELETE_TYPOLOGY',
  SECURITY_DISABLE_TYPOLOGY: 'SECURITY_DISABLE_TYPOLOGY',
  SECURITY_GET_TYPOLOGY: 'SECURITY_GET_TYPOLOGY',
  SECURITY_GET_TYPOLOGIES: 'SECURITY_GET_TYPOLOGIES',

  SECURITY_APPROVE_TYPOLOGY: 'SECURITY_APPROVE_TYPOLOGY',
  SECURITY_REJECT_TYPOLOGY: 'SECURITY_REJECT_TYPOLOGY',
  SECURITY_WITHDRAW_TYPOLOGY: 'SECURITY_WITHDRAW_TYPOLOGY',
  SECURITY_DEPLOY_TYPOLOGY: 'SECURITY_DEPLOY_TYPOLOGY',
  SECURITY_RETIRE_TYPOLOGY: 'SECURITY_RETIRE_TYPOLOGY',
  SECURITY_ARCHIVE_TYPOLOGY: 'SECURITY_ARCHIVE_TYPOLOGY',
  SECURITY_ABANDON_TYPOLOGY: 'SECURITY_ABANDON_TYPOLOGY',

  SECURITY_CREATE_TYPOLOGY_RULE_CONFIG: 'SECURITY_CREATE_TYPOLOGY_RULE_CONFIG',
  SECURITY_UPDATE_TYPOLOGY_RULE_CONFIG: 'SECURITY_UPDATE_TYPOLOGY_RULE_CONFIG',
  SECURITY_GET_TYPOLOGY_RULE_CONFIG: 'SECURITY_GET_TYPOLOGY_RULE_CONFIG',
  SECURITY_GET_TYPOLOGY_RULE_CONFIGS: 'SECURITY_GET_TYPOLOGY_RULE_CONFIGS',

  // Network Map Management 
  SECURITY_CREATE_NETWORK_MAP: 'SECURITY_CREATE_NETWORK_MAP',
  SECURITY_UPDATE_NETWORK_MAP: 'SECURITY_UPDATE_NETWORK_MAP',
  SECURITY_DELETE_NETWORK_MAP: 'SECURITY_DELETE_NETWORK_MAP',
  SECURITY_DISABLE_NETWORK_MAP: 'SECURITY_DISABLE_NETWORK_MAP',
  SECURITY_GET_NETWORK_MAP: 'SECURITY_GET_NETWORK_MAP',

  SECURITY_APPROVE_NETWORK_MAP: 'SECURITY_APPROVE_NETWORK_MAP',
  SECURITY_REJECT_NETWORK_MAP: 'SECURITY_REJECT_NETWORK_MAP',
  SECURITY_WITHDRAW_NETWORK_MAP: 'SECURITY_WITHDRAW_NETWORK_MAP',
  SECURITY_DEPLOY_NETWORK_MAP: 'SECURITY_DEPLOY_NETWORK_MAP',
  SECURITY_RETIRE_NETWORK_MAP: 'SECURITY_RETIRE_NETWORK_MAP',
  SECURITY_ARCHIVE_NETWORK_MAP: 'SECURITY_ARCHIVE_NETWORK_MAP',
  SECURITY_ABANDON_NETWORK_MAP: 'SECURITY_ABANDON_NETWORK_MAP',
  SECURITY_EXPORT_NETWORK_MAP: 'SECURITY_EXPORT_NETWORK_MAP',
  SECURITY_IMPORT_NETWORK_MAP: 'SECURITY_IMPORT_NETWORK_MAP',
};
