import classNames from "classnames";
import Head from "next/head";
import Link from "next/link";
import React from "react";

import { LanguageSelector } from "~/components/common/LanguageSelector";
import { useCommonTranslations } from "~/hooks";

import styles from "./AuthLayout.module.scss";

type LayoutPropsType = {
  children: React.ReactNode;
};

const AuthLayout = ({ children }: LayoutPropsType) => {
  const { t: commonTranslations } = useCommonTranslations();

  return (
    <>
      <Head>
        <title>LexTego - Configuration Service</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles["auth-layout"]}>
        <div className={styles["auth-layout-left"]}>
          <div className={styles["auth-header"]}>
            <img alt="logo" src="/images/logo-full-light.svg" width="220" />
          </div>
          <div className={styles["auth-main-content"]}>{children}</div>
          <div className={classNames(styles["auth-footer"], "mt-8")}>
            <div className={classNames(styles["auth-footer-links"], "flex justify-between gap-8")}>
              <LanguageSelector popupPosition={{ bottom: "10", left: "0" }} />

              <div className="flex space-x-10 items-center">
                <Link className="!text-black" href="javascript;">
                  {commonTranslations("help")}
                </Link>
                <Link className="!text-black" href="javascript;">
                  {commonTranslations("privacy")}
                </Link>
                <Link className="!text-black" href="javascript;">
                  {commonTranslations("terms")}
                </Link>
              </div>
            </div>
          </div>
        </div>
        <div className={styles["auth-layout-right"]}>
          <div className={styles["auth-layout-bg-img"]} />
        </div>
      </div>
    </>
  );
};

export { AuthLayout };
